version: '2'

services:
    sut:
        build:
            context: .
            args:
                http_proxy: ${http_proxy}
                HTTP_PROXY: ${http_proxy}
                https_proxy: ${http_proxy}
                HTTPS_PROXY: ${http_proxy}
        command: bash /run_test.sh
